name: CICD

on: push

jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.5.1
      - name: Bundle install
        run: bundle install
      - name: Run rubocop
        run: bundle exec rubocop
